services:
  - type: worker
    name: music 1
    env: docker
    dockerfilePath: ./Dockerfile
    plan: pro plus
    region: singapore
    buildCommand: pip3 install --no-cache-dir --upgrade --requirement requirements.txt
    envVars:
      - key: API_ID
        sync: ""
      - key: API_HASH
        sync: ""
      - key: STORAGE_CHANNEL_ID
        sync: ""
      - key: BOT_TOKEN
        sync: ""
      - key: MONGO_DB_URI
        sync: ""
      - key: OWNER_ID
        sync: ""
      - key: LOGGER_ID
        sync: ""
      - key: STRING_SESSION
        sync: ""
